### ISSUE TITLE
Feature Request: Add a Way to Edit Existing Prompt

### ISSUE THREAD

**Issue by cquanu** [giosilvi/GPT-Prompter#18]
I have an existing prompt that I would like to edit, but the current UI does not offer a way to edit existing prompts. It would be great to have a way to edit existing prompts so that users could adjust or customize them to their preferences. 

**Relevant Issue Details**
- Feature Name: Add a way to edit existing prompt
- Description: Allow users to edit existing prompts
- Use Case: Give users more control over their prompt customization

**Comment by giosilvi** [comment]
Hi @cquanu , I added some basic edit functionality. For the moment it basically copied the prompt with their parameter in the Prompt Design textbox, but it will not delete the old one when the user change parameters. I am not sure if it would be better to also remove the previous one as well, or is better like this, so that one can have both instances. What do you think?

**Comment by cquanu** [comment]
I think that's fine. Maybe you can follow the OpenAI playground concept where there's an save and save as new button.
