### ISSUE TITLE
insufficient_quota

### ISSUE THREAD

**Issue by anotherduckling** [giosilvi/GPT-Prompter#25]
>*You exceeded your current quota, please check your plan and billing details.*

I am using the extension in Brave. I have reinstalled the extension too with new api key. It has been verified too. But still getting the same issue.

**Comment by giosilvi** [comment]
Hi! This is a message send by OpenAI side. I highly suspect that the free credits that they provide to each new profile has been exhausted. Try to go on their website and see it yourself: https://platform.openai.com/playground . Very likely you need to provide a payment method with them to continue using it.

**Comment by anotherduckling** [comment]
![image](https://user-images.githubusercontent.com/57977673/219072061-ee124df8-0175-4948-9189-4bffc92f86c7.png)

**Comment by anotherduckling** [comment]
aa... expired
so i need to be a paid member to use this?

**Comment by giosilvi** [comment]
Yes, OpenAI offers their models via an API where the users pay per token usage. (I for example pay roughly 1-3 dollars per month for hundreds of prompts). The only free service they offer is chatGPT, but due to the limited capacity often is not available (and of course there is also chatGPT Plus for 20$ a month, this one is fixed regardless of how much you use).
